const files = {
  Documents : [
    {name:'document2', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'document7', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'document1', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'},
    {name:'document2', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'document7', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'document1', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'},
    {name:'document2', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'document7', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'document1', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'},
    {name:'document2', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'document7', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'document1', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'},
    {name:'document2', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'document7', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'document1', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'document4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'document8', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'document6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'document3', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'},
    {name:'document5', dateModified: 'Jan 1 2007', fileSize: '--', kind: '--'}
  ],
  Pictures : [
    {name:'picture1', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'picture2', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'picture3', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'picture4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'picture5', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'picture6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'},
    {name:'picture7', dateModified: 'Jan 1 2006', fileSize: '--', kind: '--'}
  ],
  Music : [
    {name:'song1', dateModified: 'Jan 1 2000', fileSize: '--', kind: '--'},
    {name:'song2', dateModified: 'Jan 1 2001', fileSize: '--', kind: '--'},
    {name:'song3', dateModified: 'Jan 1 2002', fileSize: '--', kind: '--'},
    {name:'song4', dateModified: 'Jan 1 2003', fileSize: '--', kind: '--'},
    {name:'song5', dateModified: 'Jan 1 2004', fileSize: '--', kind: '--'},
    {name:'song6', dateModified: 'Jan 1 2005', fileSize: '--', kind: '--'}
  ]
}

export {files}
